name: 'Checkout Node Project'
description: 'Checkout branch, install Node, and run `npm ci`'

inputs:
  node-version:
    description: Nodejs version to install
    required: true
    default: 16.x

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{inputs['node-version']}}

    - name: Install dependencies
      run: npm ci
